### ISSUE TITLE
Search interval for maximum mortality risk

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/simulist#103]
`optimise()` in `.add_outcome()` is run over the interval `[0, 100]` because if the upper bound of the interval is higher it can fail to find the function maximum. If the function maximum is above 100 then this code will fail to find the maximum and return the local maximum between 0 and 100 and so the code will technically be wrong.

The problem is because the user can input any anonymous function it's impossible to know where to search, but `[0, 100]` seemed realistic and is narrow enough for the search to reliably find the optimum. 

One option is to add another argument to `config` which is something along the lines of `time_varying_cfr_max_range` which by default could be `c(0, 100)`, but allows the user to change it.

_Originally posted by @joshwlambert in https://github.com/epiverse-trace/simulist/pull/101#discussion_r1572280857_

**Comment by joshwlambert** [comment]
Thanks for raising, this was a problem while we were working on the time-varying case fatality risk feature addition, however, the finalised implementation of time-varying case fatality risk in #101 did not use `optimise()`, therefore this issue no longer applies.
