### ISSUE TITLE
differenciate infectious and infected in arguments `infect_period` and `prob_infect`

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/simulist#138]
in `sim_linelist()` we use `infect_period` for the infectious period and `prob_infect` for the probability of infection on contact. The "infect" word seems to refer to the same word. 

In tutorials, we have a callout box as a reminder of their difference ([link to callout box](https://epiverse-trace.github.io/tutorials-late/simulating-transmission.html#exposed-infected-infectious)).

To emphasize this difference, Would it be feasible to make these arguments explicit? 

- from `infect_period` to `infectious_period`
- from `prob_infect` to `prob_infection` 

This would look like this:
```r
sim_linelist(
  contact_distribution = contact_distribution,
  infectious_period = infectious_period, # suggestion
  prob_infection = 0.5, # suggestion
  onset_to_hosp = onset_to_hosp,
  onset_to_death = onset_to_death,
  hosp_risk = 0.01,
  outbreak_start_date = as.Date("2019-12-01")
)
```

**Comment by joshwlambert** [comment]
Thanks for raising @avallecam! I was aware of the slight ambiguity in argument names, but felt it was still relatively clear to users. I don't have a preference on the names, as you think it is important to differentiate the two and given this is an easy change to make I will make a PR with the proposed name changes.
