### ISSUE TITLE
about the relationship between contact distribution, probability of infection, and basic reproduction number

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/simulist#139]
In this paragraph:
https://github.com/epiverse-trace/simulist/blob/4dde87cde1c5a4310abe6b39c2c04ceac79b5761/README.Rmd#L97

are we referring to the relationship in slide 25 from the resource link below?
https://www.reconlearn.org/slides/compartmental-ebola/compartmental-ebola.pdf

$R_0 = \beta D = p c D$

If it does, would it add to the documentation to make this relationship visible as an equation? 

or refer to this [paper by Bjørnstad et al.](https://www.nature.com/articles/s41592-020-0822-z) that briefly explains that relationship in the fourth paragraph before the first system of diff equations?

**Comment by joshwlambert** [comment]
Thanks for posting this @avallecam. Yes, I believe this equation matches the simulation in {simulist} (there is no depletion of susceptibles in `.sim_network_bp()` for now). Where would you recommend I add this documentation in the package?

**Comment by joshwlambert** [comment]
I've discussed how to resolve this issue with @avallecam and @jamesmbaazam, with some discussion in #151. I will now close this issue, as agreed, I will describe the {simulist} simulation in a dedicated vignette.
