### ISSUE TITLE
set risks to `NA` if processes not desired

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/simulist#146]
Setting `onset_to_hosp` to NA yields a warning

```r
Warning messages:
1: Some onset-to-event and their corresponding risk are incompatible:
  - onset_to_hosp is set to NA but hosp_risk is specified 
```

I think it should be either documented with the `onset_to_hosp` argument that this has to be done manually, or (my preference) `hosp_risk` should be set automatically if it is not specified (can use `missing()`) and `onset_to_hosp` is not wanted.

**Comment by joshwlambert** [comment]
The `hosp_risk` argument is set by default to 0.2. Is your preference to override the `hosp_risk` to `NULL` with `onset_to_hosp` is set to `NULL` and not warn the user? (`NULL` rather than `NA` since PR #147).

I'd prefer not to remove the default value for the `*_risk` arguments as we are moving in the direction of adding more default values rather than less (see #120).

**Comment by sbfnk** [comment]
How about something like 

```r
if (is.null(onset_to_hosp) && missing(hosp_risk)) {
  hosp_risk <- NULL
}
```
and add to the documentation that it's ignored if `onset_to_hosp` is non-null?

**Comment by joshwlambert** [comment]
I would like to keep the default values for the `*_risk` arguments to enable users to easily run the function without having to specify them.

The choice as I see it is between

A) No warning to users
```r
if (is.null(onset_to_hosp)) {
  hosp_risk <- NULL
}
```

B) Do not warn users that `hosp_risk` is being ignored
```r
if (is.null(onset_to_hosp) && !is.null(hosp_risk)) {
  warning(...)
  hosp_risk <- NULL
}
```

Whichever option is chosen I will improve the documentation.

**Comment by sbfnk** [comment]
> I would like to keep the default values for the *_risk arguments to enable users to easily run the function without having to specify them.

I'm not completely following - my suggestion would allow you to keep the default but warn if set by a user if they also set `onset_to_hosp` to `NULL`.

**Comment by joshwlambert** [comment]
This is a good solution, but how do you know if `hosp_risk` is set by the user when `onset_to_hosp` is set to `NULL`?

For example if `hosp_risk` is not 0.2, then you know it's been changed by the user from the default value, but what if the user sets it to 0.2 and sets `onset_to_hosp` to `NULL`, should it still warn? 

Phrased another way, is there a way to know if a user has supplied a value to an argument if that argument has a default (which precludes the use of `missing()`)?

**Comment by joshwlambert** [comment]
First and foremost apologies, I didn't understand the functionality of `missing()` fullt. It appears that `missing()` is `TRUE` even when the argument has a default value:

``` r
func <- function(x = 1) {
  print(x)
  if (missing(x)) {
    return("it is missing")
  } else {
    return("it is not missing")
  }
}
func()
#> [1] 1
#> [1] "it is missing"
```

``` r
func(x = 2)
#> [1] 2
#> [1] "it is not missing"
```

<sup>Created on 2024-07-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I'll implement the changes you suggested using `missing()`.

(Sorry, this wouldn't have taken much less back-and-forth if my knowledge of R was better).
