### ISSUE TITLE
ct distribution parameters by default are not reflected in simulated linelist

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/simulist#157]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [x] I have the most recent version of this package and R

```r
packageVersion("simulist")
#> [1] ‘0.3.0.9000’
```

 - [x] I have found a bug
 - [x] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

Please include a brief description of the problem with a code example:

``` r
library(simulist)
library(dplyr)

set.seed(111)

dat <- sim_linelist() %>% 
  as_tibble()

simulist_config <- create_config()

simulist_config$ct_distribution
#> [1] "norm"

simulist_config$ct_distribution_params
#> mean   sd 
#>   25    2

dat %>% 
  dplyr::select(ct_value) %>% 
  summary()
#>     ct_value   
#>  Min.   :24.3  
#>  1st Qu.:24.3  
#>  Median :24.3  
#>  Mean   :24.3  
#>  3rd Qu.:24.3  
#>  Max.   :24.3  
#>  NA's   :222
```

<sup>Created on 2024-09-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

All observations in the linelist have equal value, Is this expected?

---------

**Comment by joshwlambert** [comment]
Thanks for spotting this @avallecam! I've made a fix in #158 please take a look and then we can merge the changes.
