### ISSUE TITLE
Table of related packages/work

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/simulist#21]
{simulist} is a neat package that will fill in the gap of linelist generation, which is quite common in epi modeling. I see some work is currently underway to [compare features across {simulist} and other packages](https://github.com/epiverse-trace/simulist/tree/related_projs#related-projects). I would be interested in contributing to this, following up on [my previous contributions on the discussion board of this package](https://github.com/orgs/epiverse-trace/discussions/46#discussioncomment-4943338) and others on the [{epichains} discussion board](https://github.com/epiverse-trace/epichains/discussions/17) that provide some of the required functionalities here. 

I can contribute my own list of necessary and nice-to-have functionalities, review {simulist}, and help populate the table.

**Comment by joshwlambert** [comment]
@jamesmbaazam I've completed a first draft of the related projects section in the `README`. Can you please take a look and add any packages that are currently missing and give input on the fields that are being included to demonstrate features and developer activity for each package? This might be currently biased in favour of {simulist} so any input on other field is welcomed. 

I still have to look through the code Seb mentioned in #16, but once this is included in the table I will make a PR to merge into `main`. Looking to open the PR by the start of next week and then merge by the end of next week.

**Comment by joshwlambert** [comment]
Closing this issue as PR #110 adding related projects to the `README` is now merged into `main`. 

If anyone would like to add any other packages to this section or update the information, please reopen this issue or make a new one, or make a pull request.
