### ISSUE TITLE
add detailed argument description to acronym in `add_ct`

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/simulist#59]
If `add_ct` is kept #41 

I suggest complementing the argument description:

https://github.com/epiverse-trace/simulist/blob/38fc30c26c84b1d35d993329d7c5e0730627ea3b/R/sim_linelist.R#L48-L49

with one more sentence:

> (...) Default is `TRUE`. Ct refers to the Cycle threshold from a Real-time PCR or quantitative PCR (qPCR).

**Comment by joshwlambert** [comment]
Thank you for the suggestion @avallecam. Changes implemented in #62.
